-- The fixed-asset register.
--
-- GENERATED by scripts/generate-books-seed.mjs — do not hand-edit. Regenerate with
-- `npm run seed:books` if src/data/fixedAssets.ts changes.
--
-- These four are the assets the opening entry capitalises: their costs are its debits to
-- 1410/1420/1430 and the sum of openingAccumulated() over them is its credit to 1490. So
-- the register is not decoration beside the balance sheet, it is what explains it — which
-- is why it is generated from the same module rather than typed out again.

insert into public.fixed_assets
  (id, name_en, name_ar, category, cost_minor, life_months, in_service_en, in_service_ar, opening_months, center_id)
values
  ('FA-01','Cocoa production line — Jazan','خط إنتاج الكاكاو — جازان','equipment',120000000,120,'Jan 2024','يناير ٢٠٢٤',30,'CC-01'),
  ('FA-02','Refrigerated delivery vans (2)','مركبتا توصيل مبرّدتان','vehicles',48000000,72,'Jul 2024','يوليو ٢٠٢٤',24,'CC-03'),
  ('FA-03','Jazan boutique fit-out','تجهيزات معرض جازان','fixtures',27000000,60,'Mar 2025','مارس ٢٠٢٥',16,'CC-04'),
  ('FA-04','Warehouse cold-storage system','نظام التبريد بالمستودع','fixtures',36000000,96,'Jan 2025','يناير ٢٠٢٥',18,'CC-03')
on conflict (id) do nothing;
