-- The chart of accounts, the periods, and the opening book.
--
-- GENERATED by scripts/generate-books-seed.mjs — do not hand-edit. Regenerate with
-- `npm run seed:books` if src/data/coa.ts or src/data/ledgerSeed.ts changes.
--
-- The chart is not demo data: it is the spine every posting names, and without it the
-- books cannot accept a single entry, because journal_lines_require_postable() refuses
-- a line whose account is not there. The opening book IS the prototype's book — the
-- figures the executive overview, the collection tab and the purchase desk have always
-- shown, booked through the same posting rules — so the general ledger opens agreeing
-- with the screens that came before it.
--
-- ORDER MATTERS, twice over:
--   * accounts before lines (foreign key, and the postable check).
--   * every period is inserted OPEN, then the entries, then the closed ones are
--     closed. The opening entry is dated 30 June and June is a closed period, so
--     closing first would have journal_entries_period_open() refuse the very entry
--     that opens the book.
--
-- Entry and line ids are derived from the voucher number, so re-running this is a
-- no-op rather than a second copy of the book.

-- ---------------------------------------------------------------- chart (44)

insert into public.accounts
  (code, name_en, name_ar, type, normal, parent, postable, active, is_control, contra, cash, vat_role, sort_order)
values
  ('1000','Assets','الأصول','asset','debit',null,false,true,false,false,false,null,0),
  ('1100','Cash & equivalents','النقد وما في حكمه','asset','debit','1000',false,true,false,false,false,null,1),
  ('1110','Cash on hand','الصندوق','asset','debit','1100',true,true,false,false,true,null,2),
  ('1120','Bank — current account','البنك — الحساب الجاري','asset','debit','1100',true,true,false,false,true,null,3),
  ('1200','Trade receivables','الذمم المدينة التجارية','asset','debit','1000',true,true,true,false,false,null,4),
  ('1250','VAT — input tax','ضريبة القيمة المضافة — مدخلات','asset','debit','1000',true,true,false,false,false,'input',5),
  ('1300','Inventory','المخزون','asset','debit','1000',false,true,false,false,false,null,6),
  ('1310','Raw materials','مخزون المواد الخام','asset','debit','1300',true,true,false,false,false,null,7),
  ('1330','Finished goods','مخزون البضاعة التامة','asset','debit','1300',true,true,false,false,false,null,8),
  ('1340','Packaging materials','مخزون مواد التغليف','asset','debit','1300',true,true,false,false,false,null,9),
  ('1400','Property, plant & equipment','الأصول الثابتة','asset','debit','1000',false,true,false,false,false,null,10),
  ('1410','Production equipment','معدات الإنتاج','asset','debit','1400',true,true,false,false,false,null,11),
  ('1420','Cold-chain vehicles','المركبات المبرّدة','asset','debit','1400',true,true,false,false,false,null,12),
  ('1430','Fixtures & fittings','الأثاث والتجهيزات','asset','debit','1400',true,true,false,false,false,null,13),
  ('1490','Accumulated depreciation','مجمع الإهلاك','asset','credit','1400',true,true,false,true,false,null,14),
  ('2000','Liabilities','الخصوم','liability','credit',null,false,true,false,false,false,null,15),
  ('2100','Trade payables','الذمم الدائنة التجارية','liability','credit','2000',true,true,true,false,false,null,16),
  ('2150','VAT — output tax','ضريبة القيمة المضافة — مخرجات','liability','credit','2000',true,true,false,false,false,'output',17),
  ('2160','VAT payable to ZATCA','ضريبة القيمة المضافة المستحقة للهيئة','liability','credit','2000',true,true,false,false,false,'payable',18),
  ('2200','Accrued expenses','مصروفات مستحقة','liability','credit','2000',true,true,false,false,false,null,19),
  ('2300','Customer advances','دفعات مقدمة من العملاء','liability','credit','2000',true,true,false,false,false,null,20),
  ('3000','Equity','حقوق الملكية','equity','credit',null,false,true,false,false,false,null,21),
  ('3100','Share capital','رأس المال','equity','credit','3000',true,true,false,false,false,null,22),
  ('3200','Retained earnings','الأرباح المبقاة','equity','credit','3000',true,true,false,false,false,null,23),
  ('3900','Income summary','ملخص الدخل','equity','credit','3000',true,true,false,false,false,null,24),
  ('4000','Revenue','الإيرادات','revenue','credit',null,false,true,false,false,false,null,25),
  ('4100','Retail sales — B2C','مبيعات التجزئة — B2C','revenue','credit','4000',true,true,false,false,false,null,26),
  ('4200','Wholesale sales — B2B','مبيعات الجملة — B2B','revenue','credit','4000',true,true,false,false,false,null,27),
  ('4300','Export sales — MEGA','مبيعات التصدير — MEGA','revenue','credit','4000',true,true,false,false,false,null,28),
  ('4400','Shipping revenue','إيراد الشحن','revenue','credit','4000',true,true,false,false,false,null,29),
  ('4900','Sales returns & discounts','مردودات وخصومات المبيعات','revenue','debit','4000',true,true,false,true,false,null,30),
  ('5000','Costs & expenses','التكاليف والمصروفات','expense','debit',null,false,true,false,false,false,null,31),
  ('5100','Cost of goods sold','تكلفة البضاعة المباعة','expense','debit','5000',true,true,false,false,false,null,32),
  ('5200','Waste & write-offs','الهدر والإتلاف','expense','debit','5000',true,true,false,false,false,null,33),
  ('5300','Operating expenses','المصروفات التشغيلية','expense','debit','5000',false,true,false,false,false,null,34),
  ('5310','Salaries & wages','الرواتب والأجور','expense','debit','5300',true,true,false,false,false,null,35),
  ('5320','Rent','الإيجارات','expense','debit','5300',true,true,false,false,false,null,36),
  ('5330','Freight & distribution','الشحن والتوزيع','expense','debit','5300',true,true,false,false,false,null,37),
  ('5340','Marketing & brand','التسويق والعلامة','expense','debit','5300',true,true,false,false,false,null,38),
  ('5350','Bank & card fees','الرسوم البنكية والشبكة','expense','debit','5300',true,true,false,false,false,null,39),
  ('5360','Administrative expenses','المصروفات الإدارية','expense','debit','5300',true,true,false,false,false,null,40),
  ('5370','Quality & inspection','الجودة والفحص','expense','debit','5300',true,true,false,false,false,null,41),
  ('5380','Customs & export documentation','الجمارك ومستندات التصدير','expense','debit','5300',true,true,false,false,false,null,42),
  ('5900','Depreciation','الإهلاك','expense','debit','5000',true,true,false,false,false,null,43)
on conflict (code) do nothing;

-- ---------------------------------------------------------------- periods (4), all open for now

insert into public.accounting_periods (key, closed)
values
  ('2026-05',false),
  ('2026-06',false),
  ('2026-07',false),
  ('2026-08',false)
on conflict (key) do nothing;

-- ---------------------------------------------------------------- the opening book (28 entries, 101 lines)

insert into public.journal_entries
  (id, no, entry_date, source, source_ref, memo_en, memo_ar, party_en, party_ar, posted_by_en, posted_by_ar)
values
  ('40757b7f-23c7-543d-8670-b08478d7c103','JV-0001','2026-06-30','opening','OB-2026-07','Opening balances at 30 June 2026','الأرصدة الافتتاحية في ٣٠ يونيو ٢٠٢٦',null,null,'Finance department','قسم المالية'),
  ('e57286cd-c920-5087-a55d-4c99e7ac777e','JV-0002','2026-07-06','sale','INV-AR-01','Sale INV-AR-01 on account','مبيعات INV-AR-01 على الحساب','Al-Dana Markets','أسواق الدانة','Finance department','قسم المالية'),
  ('dab88a10-a426-5a56-a00a-6a612ce57269','JV-0003','2026-07-13','receipt','RCPT-AR-01','Receipt RCPT-AR-01','تحصيل RCPT-AR-01','Al-Dana Markets','أسواق الدانة','Finance department','قسم المالية'),
  ('420bb511-6070-5227-9fca-2e43b91c98dd','JV-0004','2026-07-06','sale','INV-AR-02','Sale INV-AR-02 on account','مبيعات INV-AR-02 على الحساب','Najd Hospitality Group','مجموعة نجد للضيافة','Finance department','قسم المالية'),
  ('1fce7987-45ba-5dda-9769-6f91f05785f8','JV-0005','2026-07-13','receipt','RCPT-AR-02','Receipt RCPT-AR-02','تحصيل RCPT-AR-02','Najd Hospitality Group','مجموعة نجد للضيافة','Finance department','قسم المالية'),
  ('cd78a872-6511-54c4-a28f-9b7f46e8dfbb','JV-0006','2026-07-06','sale','INV-AR-03','Sale INV-AR-03 on account','مبيعات INV-AR-03 على الحساب','Hyper Panda','هايبر بنده','Finance department','قسم المالية'),
  ('8f75e50e-e394-5e06-8680-2a11c55bd7fa','JV-0007','2026-07-13','receipt','RCPT-AR-03','Receipt RCPT-AR-03','تحصيل RCPT-AR-03','Hyper Panda','هايبر بنده','Finance department','قسم المالية'),
  ('16a86d87-bb88-5571-9108-adb13c1ab67f','JV-0008','2026-07-06','sale','INV-AR-04','Sale INV-AR-04 on account','مبيعات INV-AR-04 على الحساب','Jeddah Grand Hotel','فندق جدة الكبير','Finance department','قسم المالية'),
  ('fa3abb60-3eb9-5d39-9b5f-9575e8462d04','JV-0009','2026-07-13','receipt','RCPT-AR-04','Receipt RCPT-AR-04','تحصيل RCPT-AR-04','Jeddah Grand Hotel','فندق جدة الكبير','Finance department','قسم المالية'),
  ('e3b8a9c4-5b66-531a-bc53-96a2e894e3de','JV-0010','2026-07-06','sale','INV-AR-05','Sale INV-AR-05 on account','مبيعات INV-AR-05 على الحساب','Al-Tazaj Restaurants','مطاعم الطازج','Finance department','قسم المالية'),
  ('e1900580-a3f7-50b1-b6ca-c73406967bb9','JV-0011','2026-07-13','receipt','RCPT-AR-05','Receipt RCPT-AR-05','تحصيل RCPT-AR-05','Al-Tazaj Restaurants','مطاعم الطازج','Finance department','قسم المالية'),
  ('bf32384c-d28c-5c9f-9894-11d5b9f0c24f','JV-0012','2026-07-06','sale','INV-AR-06','Sale INV-AR-06 on account','مبيعات INV-AR-06 على الحساب','Aseer Events LLC','عسير للفعاليات','Finance department','قسم المالية'),
  ('2c433953-68dc-5bf8-819d-cb8adeb54509','JV-0013','2026-07-13','receipt','RCPT-AR-06','Receipt RCPT-AR-06','تحصيل RCPT-AR-06','Aseer Events LLC','عسير للفعاليات','Finance department','قسم المالية'),
  ('db9a9d44-3250-59b7-a128-7a9ee2960623','JV-0014','2026-07-06','sale','RT-2607-W1','Sale RT-2607-W1','مبيعات RT-2607-W1','Boutique takings — week 1','مبيعات المعارض — الأسبوع الأول','Finance department','قسم المالية'),
  ('024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','JV-0015','2026-07-13','sale','RT-2607-W2','Sale RT-2607-W2','مبيعات RT-2607-W2','Boutique takings — week 2','مبيعات المعارض — الأسبوع الثاني','Finance department','قسم المالية'),
  ('bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','JV-0016','2026-07-20','sale','RT-2607-W3','Sale RT-2607-W3','مبيعات RT-2607-W3','Boutique takings — week 3','مبيعات المعارض — الأسبوع الثالث','Finance department','قسم المالية'),
  ('0c30b37c-7946-5adb-aa12-fe50d38f1fcd','JV-0017','2026-07-06','purchase','PINV-3312','Purchase invoice PINV-3312','فاتورة شراء PINV-3312','Barry Callebaut','باري كاليبو','Finance department','قسم المالية'),
  ('0058e070-3786-5607-829b-67c29773a356','JV-0018','2026-07-06','purchase','PINV-3310','Purchase invoice PINV-3310','فاتورة شراء PINV-3310','Almarai','المراعي','Finance department','قسم المالية'),
  ('776330bd-8498-50a5-b1de-2eb78ed1826a','JV-0019','2026-07-06','purchase','PINV-3307','Purchase invoice PINV-3307','فاتورة شراء PINV-3307','Nut Traders','تجار المكسّرات','Finance department','قسم المالية'),
  ('4faccdb2-c27e-5fba-b8e7-82809760aa5e','JV-0020','2026-07-06','purchase','PINV-3301','Purchase invoice PINV-3301','فاتورة شراء PINV-3301','Jizan Press','مطابع جيزان','Finance department','قسم المالية'),
  ('6d8b49b1-1a5e-532f-8283-4e75d57fbcd7','JV-0021','2026-07-13','waste','W-1','Write-off — Near expiry','هدر — قرب الانتهاء','Rose box · BATCH-FG-091','بوكس الورد · BATCH-FG-091','Hind Al-Asiri — production','هند العسيري — الإنتاج'),
  ('0b745470-b195-51d3-9f8e-25e1c2585d66','JV-0022','2026-07-13','waste','W-2','Write-off — Melted in transit','هدر — ذابت أثناء النقل','Milk bars','ألواح حليب','Salem Al-Ghamdi — warehouse','سالم الغامدي — أمين المستودع'),
  ('d8081785-aa46-51c3-89b1-fcc8e82a6e76','JV-0023','2026-07-13','waste','W-3','Write-off — Processing loss','هدر — فاقد تصنيع','Cocoa mass','كتلة كاكاو','Hind Al-Asiri — production','هند العسيري — الإنتاج'),
  ('1fd074cb-9a87-5614-9b00-55498d341a0b','JV-0024','2026-07-13','waste','W-4','Write-off — Print defects','هدر — عيوب طباعة','Gold foil','ورق ذهبي','Salem Al-Ghamdi — warehouse','سالم الغامدي — أمين المستودع'),
  ('38ae3f5c-6f1f-5136-aa71-f2b21100c2ee','JV-0025','2026-07-20','cost_center','RT-2607-W1..W3','Boutiques — retail floor — load on RT-2607-W1..W3','المعارض — التجزئة — تحميل على RT-2607-W1..W3','Boutique retail floor','أرضية المعارض','Finance department','قسم المالية'),
  ('ba263620-97e5-5826-95d8-c105cfee944c','JV-0026','2026-07-20','cost_center','INV-AR-03','Cold-chain & distribution — load on INV-AR-03','سلسلة التبريد والتوزيع — تحميل على INV-AR-03','Hyper Panda','هايبر بنده','Finance department','قسم المالية'),
  ('b4675828-5293-5e97-ba4e-79a0b71f42e1','JV-0027','2026-07-20','cost_center','INV-AR-01','Export & GCC accounts — load on INV-AR-01','التصدير وحسابات الخليج — تحميل على INV-AR-01','Al-Dana Markets','أسواق الدانة','Finance department','قسم المالية'),
  ('ee714eb1-bbcd-5724-802b-367808a37015','JV-0028','2026-07-31','depreciation','DEP-2026-07','Depreciation for 2026-07','إهلاك الفترة 2026-07',null,null,'Finance department','قسم المالية')
on conflict (id) do nothing;

insert into public.journal_lines
  (id, entry_id, account_code, debit_minor, credit_minor, center_id, memo_en, memo_ar, "position")
values
  ('85b0162f-aa26-50c5-9e57-6469ef4b428b','40757b7f-23c7-543d-8670-b08478d7c103','1110',1500000,0,null,null,null,0),
  ('3a91b326-3d0d-56c3-a500-486bf5e9b96a','40757b7f-23c7-543d-8670-b08478d7c103','1120',48000000,0,null,null,null,1),
  ('86af42cb-9251-5131-a476-9caaa668dcb2','40757b7f-23c7-543d-8670-b08478d7c103','1310',12600000,0,null,null,null,2),
  ('1815aa10-f855-5c82-b7be-27655cf52db8','40757b7f-23c7-543d-8670-b08478d7c103','1330',186400000,0,null,null,null,3),
  ('6d46afb0-f759-5832-a95b-863074c9f2de','40757b7f-23c7-543d-8670-b08478d7c103','1410',120000000,0,null,null,null,4),
  ('2da55b4e-5621-51b5-a47d-d22be176cd75','40757b7f-23c7-543d-8670-b08478d7c103','1420',48000000,0,null,null,null,5),
  ('369678b2-dc4d-58d0-af94-fad1ab660dee','40757b7f-23c7-543d-8670-b08478d7c103','1430',63000000,0,null,null,null,6),
  ('0741bccf-5493-5ca9-bfe3-10f0e84305da','40757b7f-23c7-543d-8670-b08478d7c103','1490',0,59950000,null,null,null,7),
  ('ea7ac67a-432b-5b70-87eb-3a26d5e80aec','40757b7f-23c7-543d-8670-b08478d7c103','3100',0,419550000,null,null,null,8),
  ('730a0f5f-0dbf-5048-9f63-5f1ba2ac4acd','e57286cd-c920-5087-a55d-4c99e7ac777e','1200',66000000,0,null,null,null,0),
  ('fc8d050f-7cd8-56c5-910a-318cd4a42d85','e57286cd-c920-5087-a55d-4c99e7ac777e','4300',0,57391304,null,null,null,1),
  ('4bea04b4-38e3-58ab-a70e-9456058eb5ab','e57286cd-c920-5087-a55d-4c99e7ac777e','2150',0,8608696,null,null,null,2),
  ('4205d479-b2bd-5d71-9520-1d5f21fc8311','e57286cd-c920-5087-a55d-4c99e7ac777e','5100',32872771,0,null,null,null,3),
  ('bbf93764-8ec1-5535-918f-a8b8a9e60ba1','e57286cd-c920-5087-a55d-4c99e7ac777e','1330',0,32872771,null,null,null,4),
  ('57892178-791d-5e51-b48e-8a9d4115efab','dab88a10-a426-5a56-a00a-6a612ce57269','1120',39600000,0,null,null,null,0),
  ('529780c8-f6b9-5110-b537-8a4c07f6bb8d','dab88a10-a426-5a56-a00a-6a612ce57269','1200',0,39600000,null,null,null,1),
  ('03410a18-d0bb-517f-a68c-f33d0091f147','420bb511-6070-5227-9fca-2e43b91c98dd','1200',12050000,0,null,null,null,0),
  ('c934b5bf-009b-5689-869b-bed742bad716','420bb511-6070-5227-9fca-2e43b91c98dd','4200',0,10478261,null,null,null,1),
  ('c0c4131a-b374-5f67-8b21-485a6dc97a2a','420bb511-6070-5227-9fca-2e43b91c98dd','2150',0,1571739,null,null,null,2),
  ('9f1fc296-ea84-5dd8-a24e-187c97ca6585','420bb511-6070-5227-9fca-2e43b91c98dd','5100',6001771,0,null,null,null,3),
  ('ddecea52-3436-5d0e-b0c8-0067f22ca37d','420bb511-6070-5227-9fca-2e43b91c98dd','1330',0,6001771,null,null,null,4),
  ('2fecd046-fc4f-5bee-933b-13d7a6a4ef37','1fce7987-45ba-5dda-9769-6f91f05785f8','1120',7230000,0,null,null,null,0),
  ('397d2023-a226-5c3d-951f-5055de58cdb7','1fce7987-45ba-5dda-9769-6f91f05785f8','1200',0,7230000,null,null,null,1),
  ('86255946-7938-58be-9373-f0056c20953c','cd78a872-6511-54c4-a28f-9b7f46e8dfbb','1200',88000000,0,null,null,null,0),
  ('3c15c20c-1cb7-522a-bfed-66bb81aa5a71','cd78a872-6511-54c4-a28f-9b7f46e8dfbb','4300',0,76521739,null,null,null,1),
  ('146ba9dc-9815-557c-ab97-2be3ba7e3b51','cd78a872-6511-54c4-a28f-9b7f46e8dfbb','2150',0,11478261,null,null,null,2),
  ('f3ad1bcc-2868-5145-9a52-bcb474f5c85a','cd78a872-6511-54c4-a28f-9b7f46e8dfbb','5100',43830362,0,null,null,null,3),
  ('13191abf-6dea-5857-9d6e-da56f4a300ba','cd78a872-6511-54c4-a28f-9b7f46e8dfbb','1330',0,43830362,null,null,null,4),
  ('32882739-bf4b-549d-b6e1-318f098a5606','8f75e50e-e394-5e06-8680-2a11c55bd7fa','1120',52800000,0,null,null,null,0),
  ('c771c184-a72f-5385-8fe5-bcbd579858e2','8f75e50e-e394-5e06-8680-2a11c55bd7fa','1200',0,52800000,null,null,null,1),
  ('3d174eef-3753-5520-9bc9-d5ab41c1641b','16a86d87-bb88-5571-9108-adb13c1ab67f','1200',7950000,0,null,null,null,0),
  ('e178ecf7-72cb-5e1b-9198-7ed028b31849','16a86d87-bb88-5571-9108-adb13c1ab67f','4200',0,6913043,null,null,null,1),
  ('bf1c400b-c0bc-59f7-ba42-50c5e082d503','16a86d87-bb88-5571-9108-adb13c1ab67f','2150',0,1036957,null,null,null,2),
  ('9e5be593-aa4b-5775-a88b-59bdbd4c1a20','16a86d87-bb88-5571-9108-adb13c1ab67f','5100',3959674,0,null,null,null,3),
  ('cd40841c-17b8-54bc-9e8d-0abca320e686','16a86d87-bb88-5571-9108-adb13c1ab67f','1330',0,3959674,null,null,null,4),
  ('df07de41-80cb-54d5-b455-29a3302b4f1a','fa3abb60-3eb9-5d39-9b5f-9575e8462d04','1120',4770000,0,null,null,null,0),
  ('6a3f463d-eb85-58b7-b038-5c49ab172c40','fa3abb60-3eb9-5d39-9b5f-9575e8462d04','1200',0,4770000,null,null,null,1),
  ('ed64bf27-e0f4-5113-86e3-b07a57618d1f','e3b8a9c4-5b66-531a-bc53-96a2e894e3de','1200',3100000,0,null,null,null,0),
  ('fc475291-424f-59c9-bdab-c2d5c0bd5e60','e3b8a9c4-5b66-531a-bc53-96a2e894e3de','4200',0,2695652,null,null,null,1),
  ('0b1bd258-7480-5197-a69c-6fd1f8e568de','e3b8a9c4-5b66-531a-bc53-96a2e894e3de','2150',0,404348,null,null,null,2),
  ('c9deedf0-e5b6-5dd3-9bc5-e6a9edf22de2','e3b8a9c4-5b66-531a-bc53-96a2e894e3de','5100',1544024,0,null,null,null,3),
  ('fb8c6160-2258-5994-b598-1842e8cb9686','e3b8a9c4-5b66-531a-bc53-96a2e894e3de','1330',0,1544024,null,null,null,4),
  ('1405b05f-2d1a-5aaa-8435-fc8ea626ad9b','e1900580-a3f7-50b1-b6ca-c73406967bb9','1120',1860000,0,null,null,null,0),
  ('05d4367a-7b34-50e4-adfd-9ae471919ad7','e1900580-a3f7-50b1-b6ca-c73406967bb9','1200',0,1860000,null,null,null,1),
  ('455fc4e1-81b7-5bdb-80df-214752f25f0e','bf32384c-d28c-5c9f-9894-11d5b9f0c24f','1200',6900000,0,null,null,null,0),
  ('79b70dcb-6288-540e-aa25-07a4480c4869','bf32384c-d28c-5c9f-9894-11d5b9f0c24f','4200',0,6000000,null,null,null,1),
  ('9c6f2276-ff74-5f6e-9df4-1820385f51fa','bf32384c-d28c-5c9f-9894-11d5b9f0c24f','2150',0,900000,null,null,null,2),
  ('d223a4b8-5d2d-5a72-bc12-a232c3e9e04a','bf32384c-d28c-5c9f-9894-11d5b9f0c24f','5100',3436699,0,null,null,null,3),
  ('39010fca-f58f-5428-8e8b-0a738fb50022','bf32384c-d28c-5c9f-9894-11d5b9f0c24f','1330',0,3436699,null,null,null,4),
  ('9bec1dee-0dc9-548c-9483-ec7670b9e61b','2c433953-68dc-5bf8-819d-cb8adeb54509','1120',4140000,0,null,null,null,0),
  ('2529ce92-a103-5e8a-9847-51ec65f49736','2c433953-68dc-5bf8-819d-cb8adeb54509','1200',0,4140000,null,null,null,1),
  ('d59eeabf-6a32-5c0c-bd9c-2d4090e0f2e2','db9a9d44-3250-59b7-a128-7a9ee2960623','1120',46000000,0,'CC-04',null,null,0),
  ('e2730169-4779-59d7-87fe-b94fe6382b7a','db9a9d44-3250-59b7-a128-7a9ee2960623','4100',0,40000000,'CC-04',null,null,1),
  ('9d7197dc-6c28-53ac-8c1e-f0eb75e22b90','db9a9d44-3250-59b7-a128-7a9ee2960623','2150',0,6000000,null,null,null,2),
  ('a4fc3e20-dfd6-553f-8769-5d9d1b4d857c','db9a9d44-3250-59b7-a128-7a9ee2960623','5100',22911326,0,'CC-04',null,null,3),
  ('d7e152ef-0871-5b0f-b5b2-12d2ca8f581e','db9a9d44-3250-59b7-a128-7a9ee2960623','1330',0,22911326,null,null,null,4),
  ('65aab478-bec2-5267-812f-cbb96caa7e89','024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','1120',50600000,0,'CC-04',null,null,0),
  ('5a94a12e-332d-5b08-8231-068d256ca939','024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','4100',0,44000000,'CC-04',null,null,1),
  ('d0720ad8-f188-586d-91f3-72c8ceab47df','024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','2150',0,6600000,null,null,null,2),
  ('7dce3e93-878f-50a2-9c74-6725c96f541a','024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','5100',25202458,0,'CC-04',null,null,3),
  ('234fe7b7-5375-5f49-8930-751faf1f3d4a','024b4f2e-3e88-5a84-a3b2-f1096a74e0f8','1330',0,25202458,null,null,null,4),
  ('042ad31f-88e1-5130-b18f-6221a7159dbe','bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','1120',46862501,0,'CC-04',null,null,0),
  ('fdf2f530-ca81-5553-b668-b322bd3fbf77','bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','4100',0,40750001,'CC-04',null,null,1),
  ('487bd8ca-077e-5822-8d33-ec8c3bb9451b','bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','2150',0,6112500,null,null,null,2),
  ('45b62fc6-92fd-569b-aa1d-634f0431684e','bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','5100',23340915,0,'CC-04',null,null,3),
  ('99d8cdee-de07-52a7-97bf-187a0a166ba6','bb7fa4a1-3b6f-580d-8d9a-0e5a9e898d49','1330',0,23340915,null,null,null,4),
  ('9c2dc8a1-bfd0-535d-91e1-d8e05e159529','0c30b37c-7946-5adb-aa12-fe50d38f1fcd','1310',23000000,0,null,null,null,0),
  ('5b85d360-96a3-55ab-b374-f3cfbf96e567','0c30b37c-7946-5adb-aa12-fe50d38f1fcd','1250',3450000,0,null,null,null,1),
  ('ec4dd57e-2a00-54f8-9208-79d78911c2b6','0c30b37c-7946-5adb-aa12-fe50d38f1fcd','1120',0,26450000,null,null,null,2),
  ('5d5db755-4a4d-510b-9fa1-1cac01cc3423','0058e070-3786-5607-829b-67c29773a356','1310',5940000,0,null,null,null,0),
  ('2e8ac4aa-b9b0-5787-9801-cc7393569526','0058e070-3786-5607-829b-67c29773a356','1250',891000,0,null,null,null,1),
  ('855c29f3-5787-5b3c-a4b4-e419df710d90','0058e070-3786-5607-829b-67c29773a356','2100',0,6831000,null,null,null,2),
  ('8964aaa4-eac8-5e62-bced-fae791a1b41c','776330bd-8498-50a5-b1de-2eb78ed1826a','1310',1120000,0,null,null,null,0),
  ('2cbd267a-5976-522a-90df-a68e2096e861','776330bd-8498-50a5-b1de-2eb78ed1826a','1250',168000,0,null,null,null,1),
  ('84b51e48-58d8-5e4c-8b61-d7c071517822','776330bd-8498-50a5-b1de-2eb78ed1826a','2100',0,1288000,null,null,null,2),
  ('c6906823-b31c-53f0-9dbb-4e27be9f5356','4faccdb2-c27e-5fba-b8e7-82809760aa5e','1340',1360000,0,null,null,null,0),
  ('46962844-8a2b-5618-a05e-2d09239b4564','4faccdb2-c27e-5fba-b8e7-82809760aa5e','1250',204000,0,null,null,null,1),
  ('d4dd5985-fe00-5dd5-acbc-1f4380bce969','4faccdb2-c27e-5fba-b8e7-82809760aa5e','2100',0,1564000,null,null,null,2),
  ('000d11d9-629d-5609-982e-ca385a773759','6d8b49b1-1a5e-532f-8283-4e75d57fbcd7','5200',372000,0,null,'Rose box · BATCH-FG-091','بوكس الورد · BATCH-FG-091',0),
  ('f054bd43-6afc-5bbb-8d8c-d64457f429dd','6d8b49b1-1a5e-532f-8283-4e75d57fbcd7','1330',0,372000,null,null,null,1),
  ('4125f8a5-b97f-5749-ac5d-9f37f5d268a1','0b745470-b195-51d3-9f8e-25e1c2585d66','5200',186000,0,null,'Milk bars','ألواح حليب',0),
  ('4d50848a-2cff-5061-a734-486609472e4a','0b745470-b195-51d3-9f8e-25e1c2585d66','1330',0,186000,null,null,null,1),
  ('ba47b669-5ada-54af-ba69-d85b02d53f53','d8081785-aa46-51c3-89b1-fcc8e82a6e76','5200',164000,0,null,'Cocoa mass','كتلة كاكاو',0),
  ('32d951ea-5346-5380-904d-112176e8c7b7','d8081785-aa46-51c3-89b1-fcc8e82a6e76','1310',0,164000,null,null,null,1),
  ('ff3ac0fb-887e-51e1-ad62-578f0b1da873','1fd074cb-9a87-5614-9b00-55498d341a0b','5200',112000,0,null,'Gold foil','ورق ذهبي',0),
  ('53e5ade4-6405-5f75-9507-945aefed98dc','1fd074cb-9a87-5614-9b00-55498d341a0b','1310',0,112000,null,null,null,1),
  ('7c37e38f-e9cd-563f-bc49-3de2dc735414','38ae3f5c-6f1f-5136-aa71-f2b21100c2ee','5350',6237500,0,'CC-04','Boutique commission','عمولة المعرض',0),
  ('62a1c9e2-637d-5797-b9ce-abf2408505d8','38ae3f5c-6f1f-5136-aa71-f2b21100c2ee','5350',2183125,0,'CC-04','Card & POS fees','رسوم الشبكة ونقاط البيع',1),
  ('2f90bd9e-90a9-526c-a1b5-c0fbc181d82b','38ae3f5c-6f1f-5136-aa71-f2b21100c2ee','2200',0,8420625,null,null,null,2),
  ('6abbf981-fa7e-5b82-97ae-46de77355a06','ba263620-97e5-5826-95d8-c105cfee944c','5330',3080000,0,'CC-03','Cold-chain shipping','شحن مبرّد',0),
  ('195afde9-4964-58c7-adbd-fbc3eeee0cf4','ba263620-97e5-5826-95d8-c105cfee944c','5330',234000,0,'CC-03','Ice-pack & insulation','ثلج وعوازل',1),
  ('d8656b85-abb4-56f1-a57f-c2114cd930b4','ba263620-97e5-5826-95d8-c105cfee944c','5330',528000,0,'CC-03','Warehouse storage','تخزين بالمستودع',2),
  ('3961c6fc-12b7-56d5-9229-abaca85126b5','ba263620-97e5-5826-95d8-c105cfee944c','2200',0,3842000,null,null,null,3),
  ('4df70db5-8ae2-5a02-a82c-deedf1bcce43','b4675828-5293-5e97-ba4e-79a0b71f42e1','5380',40000,0,'CC-05','Export documentation','مستندات التصدير',0),
  ('162df803-3fa2-5958-b0cb-45051cb2ba3e','b4675828-5293-5e97-ba4e-79a0b71f42e1','5380',792000,0,'CC-05','Cargo insurance','تأمين الشحنة',1),
  ('b8d254e2-54be-51eb-856e-3f808eaa1a63','b4675828-5293-5e97-ba4e-79a0b71f42e1','2200',0,832000,null,null,null,2),
  ('e1025bf2-85b4-5a2e-aa1a-15364715ef81','ee714eb1-bbcd-5724-802b-367808a37015','5900',1000000,0,'CC-01','Cocoa production line — Jazan','خط إنتاج الكاكاو — جازان',0),
  ('d6ebc81f-4bf4-54fc-8b91-e5e9b3d595f3','ee714eb1-bbcd-5724-802b-367808a37015','5900',666667,0,'CC-03','Refrigerated delivery vans (2)','مركبتا توصيل مبرّدتان',1),
  ('2ab79058-9d16-56b7-aa24-7761a81b62a3','ee714eb1-bbcd-5724-802b-367808a37015','5900',450000,0,'CC-04','Jazan boutique fit-out','تجهيزات معرض جازان',2),
  ('528d40c9-8ead-5f29-bf48-db206a957cf1','ee714eb1-bbcd-5724-802b-367808a37015','5900',375000,0,'CC-03','Warehouse cold-storage system','نظام التبريد بالمستودع',3),
  ('ccb65bd4-45cc-5394-8e82-d7c9a1fd1bba','ee714eb1-bbcd-5724-802b-367808a37015','1490',0,2491667,null,null,null,4)
on conflict (id) do nothing;

-- ---------------------------------------------------------------- now close what is closed (2)
--
-- Last, for the reason given at the top: the opening entry lands in June, and June is
-- shut once the book has been written into it.

update public.accounting_periods set closed = true, closed_at = '2026-06-03', closed_by_en = 'Finance department', closed_by_ar = 'قسم المالية' where key = '2026-05';
update public.accounting_periods set closed = true, closed_at = '2026-07-04', closed_by_en = 'Finance department', closed_by_ar = 'قسم المالية' where key = '2026-06';
